language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - echo "Skipping install"

script:
  - echo "Skipping tests"

deploy:
  provider: azure_web_apps
  verbose: true